export const restaurant = {
  name: 'FLŌ',
  tagline: 'Modern Bistro · Riga',
  description: 'Bold. Seasonal. Made with passion.',
  highlight1: 'Open Late Fri–Sat until 23:30',
  highlight2: 'Private Events Available',
  phone: '+371 27012661',
  email: 'reservations@floresto.lv',
  address: '11.novembra krastmala 13, Rīga, LV-1050',
  instagram: 'https://instagram.com/floresto.lv',
  mapsLink: 'https://maps.google.com',
  hours: {
    weekday: 'Mon–Thu: 12:00–22:00',
    friday: 'Fri–Sat: 12:00–23:30',
    sunday: 'Sun: 12:00–21:00',
  },
  heroVideo: '/videos/intro.mp4',
  heroVideoStart: 3.3,
  aboutVideo: '/videos/worran eating.mp4',
  cinematicVideo: '/videos/closeup sauce pour.mp4',
  colors: {
    primary: '#C8102E',
    primaryDark: '#8B0A1F',
    bg: '#FDFCFA',
    bgAlt: '#F8F4EF',
    text: '#0E0A08',
    gray: '#6B6460',
  },
  menu: {
    Starters: [
      { name: 'Artsy Tartare', desc: 'Avocado, ponzu, sesame crisp, microgreens', price: '€18', img: '/images/artsy tartar.jpg' },
      { name: 'Pretty Bowl', desc: 'Seasonal vegetables, tahini, herbs', price: '€14', img: '/images/pretty-bowl.jpg' },
      { name: 'White Bowl', desc: 'Cold-pressed olive oil, basil oil, sea salt', price: '€16', img: '/images/white bowl.jpg' },
    ],
    Mains: [
      { name: 'Pan-Seared Sea Bass', desc: 'Cauliflower purée, capers, brown butter', price: '€26', img: '/images/white bowl.jpg' },
      { name: 'Dry-Aged Ribeye', desc: '28-day aged, bone marrow butter, truffle fries', price: '€38', img: '/images/artsy tartar.jpg' },
      { name: 'Wild Mushroom Risotto', desc: 'Porcini, aged Parmesan, truffle oil', price: '€22', img: '/images/pretty-bowl.jpg' },
    ],
    Desserts: [
      { name: 'Crème Brûlée', desc: 'Vanilla bean, caramelised crust', price: '€10', img: '/images/white bowl.jpg' },
      { name: 'Dark Chocolate Fondant', desc: 'Salted caramel core, vanilla ice cream', price: '€12', img: '/images/pretty-bowl.jpg' },
      { name: 'Tiramisu', desc: 'Mascarpone, espresso-soaked ladyfingers', price: '€11', img: '/images/artsy tartar.jpg' },
    ],
  },
  reviews: [
    { stars: 5, text: 'The tartare is absolutely unreal. Best starter in Riga, no contest.', name: 'Marta K.', time: '2 weeks ago', tags: ['Tartare', 'Starters'] },
    { stars: 5, text: 'FLŌ hosted our company dinner for 40 people. Flawless from start to finish.', name: 'Andris B.', time: '1 week ago', tags: ['Events', 'Groups'] },
    { stars: 5, text: 'Finally a spot in Riga that takes its wine list seriously.', name: 'Sofia L.', time: '3 days ago', tags: ['Wine', 'Mains'] },
    { stars: 5, text: 'Brought my family for a birthday. The ribeye alone is worth the visit.', name: 'Jānis R.', time: '1 month ago', tags: ['Family', 'Mains'] },
    { stars: 5, text: 'The burrata is the best I have had outside of Italy.', name: 'Elīna P.', time: '2 weeks ago', tags: ['Starters', 'Regular'] },
    { stars: 5, text: 'Stumbled in at 11pm. Fresh food, fast service. Outstanding risotto.', name: 'Dāvids K.', time: '5 days ago', tags: ['Late Night', 'Mains'] },
  ],
}
