export const restaurant = {
  name: 'Bouquets by Liz',
  tagline: 'NYC Flowers · Gifts & Floral Arrangements',
  description: 'Bold. Handcrafted. Delivered across all 5 boroughs.',
  highlight1: 'Hotel Decor & Party Events',
  highlight2: 'Same-Day Delivery Available',
  phone: '',
  email: '',
  address: 'Queens, New York City',
  instagram: 'https://instagram.com/bouquetsby_liz',
  tiktok: 'https://tiktok.com/@bouquetsby_liz',
  mapsLink: 'https://maps.google.com',
  hours: {
    weekday: 'Mon–Fri: 9:00–19:00',
    friday: 'Sat: 9:00–18:00',
    sunday: 'Sun: 10:00–16:00',
  },
  heroVideo: '/videos/hero.mp4',
  heroVideoStart: 0,
  aboutVideo: '/videos/about.mp4',
  cinematicVideo: '/videos/cinematic.mp4',
  colors: {
    primary: '#B47FD4',
    primaryDark: '#8B5FA8',
    bg: '#0A0A0A',
    bgAlt: '#111111',
    text: '#F5F0EB',
    gray: '#9A9090',
  },
  menu: {
    Bouquets: [
      { name: 'Classic Rose Bouquet', desc: 'Fresh roses wrapped in premium paper — available in any color', price: 'Contact for Pricing', img: '/images/products/bouquet-rose.jpg' },
      { name: 'Letter Bouquet', desc: 'Roses arranged in your initial — a signature Liz style', price: 'Contact for Pricing', img: '/images/products/bouquet-letter.jpg' },
      { name: 'Birthday Bouquet', desc: 'Bold, colorful birthday arrangement — made to celebrate in style', price: 'Contact for Pricing', img: '/images/products/birthday-bouquet.jpg' },
    ],
    Events: [
      { name: 'Hotel Room Decor', desc: 'Full romantic setup — roses, balloons, lighting', price: 'Contact for Pricing', img: '/images/products/event-hotel.jpg' },
      { name: 'Birthday Party Setup', desc: 'Balloon arch, florals, backdrop — all 5 boroughs', price: 'Contact for Pricing', img: '/images/products/event-birthday.jpg' },
      { name: 'Floral Arch Install', desc: 'Custom event arch with premium blooms', price: 'Contact for Pricing', img: '/images/products/event-arch.jpg' },
    ],
    Gifts: [
      { name: 'Strawberry Bouquet', desc: 'Fresh strawberries arranged bouquet-style — a crowd favourite', price: 'Contact for Pricing', img: '/images/products/gift-strawberry.jpg' },
      { name: 'Strawberry Box', desc: 'Chocolate-dipped strawberries in a premium gift box', price: 'Contact for Pricing', img: '/images/products/strawberry-box.jpg' },
    ],
  },
  reviews: [
    { stars: 5, text: 'Liz set up our hotel room for our anniversary. Roses everywhere, balloons, the whole thing. My wife cried happy tears.', name: 'Marcus T.', time: '3 days ago', tags: ['Hotel Decor', 'Anniversary'] },
    { stars: 5, text: 'Ordered a letter bouquet for my mum\'s birthday. The A in roses was stunning. Same-day delivery too.', name: 'Jasmine R.', time: '1 week ago', tags: ['Letter Bouquet', 'Delivery'] },
    { stars: 5, text: 'She did the florals for my daughter\'s quinceañera. Every single guest was asking for her contact.', name: 'Carmen V.', time: '2 weeks ago', tags: ['Events', 'Party'] },
    { stars: 5, text: 'The strawberry bouquet was the most unique gift I\'ve ever given. Presentation was immaculate.', name: 'DeShawn M.', time: '5 days ago', tags: ['Gifts', 'Unique'] },
    { stars: 5, text: 'Fast delivery to the Bronx, flowers were fresh and beautiful. Will order every month.', name: 'Aisha P.', time: '2 weeks ago', tags: ['Delivery', 'Bronx'] },
    { stars: 5, text: 'Liz styled our brand pop-up event in Manhattan. The arch alone stopped people in the street.', name: 'Tyler B.', time: '1 month ago', tags: ['Events', 'Corporate'] },
  ],
}
